//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace EagleLibrary
{
    namespace EagleXML
    {
        using System.Xml.Serialization;


        /// <remarks/>
        [System.SerializableAttribute()]
        public partial class eagle
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
            public compatibility compatibility;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
            public drawing drawing;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("compatibility", Order = 2)]
            public compatibility compatibility1;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string version;
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public partial class compatibility
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("note")]
            public note[] note;
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public partial class note
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string version;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public noteSeverity severity;

            /// <remarks/>
            [System.Xml.Serialization.XmlTextAttribute()]
            public string Value;
        }

        /// <remarks/>

        [System.SerializableAttribute()]
        public enum noteSeverity
        {

            /// <remarks/>
            info,

            /// <remarks/>
            warning,

            /// <remarks/>
            error,
        }

        [System.SerializableAttribute()]
        public partial class drawing
        {

            /// <remarks/>
            public settings settings;

            /// <remarks/>
            public grid grid;

            /// <remarks/>
            public layers layers;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("board", typeof(board))]
            public board board;

            [System.Xml.Serialization.XmlElementAttribute("library", typeof(library))]
            public library library;

            [System.Xml.Serialization.XmlElementAttribute("schematic", typeof(schematic))]
            public schematic schematic;

        }

        [System.SerializableAttribute()]
        public partial class settings
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("setting")]
            public setting[] setting;
        }

        [System.SerializableAttribute()]
        public partial class setting
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public settingAlwaysvectorfont alwaysvectorfont;

            /// <remarks/>
            [System.Xml.Serialization.XmlIgnoreAttribute()]
            public bool alwaysvectorfontSpecified;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(settingVerticaltext.up)]
            public settingVerticaltext verticaltext;

            public setting()
            {
                this.verticaltext = settingVerticaltext.up;
            }
        }

        /// <remarks/>

        [System.SerializableAttribute()]
        public enum settingAlwaysvectorfont
        {

            /// <remarks/>
            no,

            /// <remarks/>
            yes,
        }

        /// <remarks/>

        [System.SerializableAttribute()]
        public enum settingVerticaltext
        {

            /// <remarks/>
            up,

            /// <remarks/>
            down,
        }

        /// <remarks/>

        [System.SerializableAttribute()]


        public partial class grid
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string distance;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public gridUnitdist unitdist;

            /// <remarks/>
            [System.Xml.Serialization.XmlIgnoreAttribute()]
            public bool unitdistSpecified;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public gridUnit unit;

            /// <remarks/>
            [System.Xml.Serialization.XmlIgnoreAttribute()]
            public bool unitSpecified;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(gridStyle.lines)]
            public gridStyle style;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("1")]
            public string multiple;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(gridDisplay.no)]
            public gridDisplay display;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string altdistance;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public gridAltunitdist altunitdist;

            /// <remarks/>
            [System.Xml.Serialization.XmlIgnoreAttribute()]
            public bool altunitdistSpecified;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public gridAltunit altunit;

            /// <remarks/>
            [System.Xml.Serialization.XmlIgnoreAttribute()]
            public bool altunitSpecified;

            public grid()
            {
                this.style = gridStyle.lines;
                this.multiple = "1";
                this.display = gridDisplay.no;
            }
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum gridUnitdist
        {

            /// <remarks/>
            mic,

            /// <remarks/>
            mm,

            /// <remarks/>
            mil,

            /// <remarks/>
            inch,
        }

        /// <remarks/>

        [System.SerializableAttribute()]
        public enum gridUnit
        {

            /// <remarks/>
            mic,

            /// <remarks/>
            mm,

            /// <remarks/>
            mil,

            /// <remarks/>
            inch,
        }

        /// <remarks/>

        [System.SerializableAttribute()]
        public enum gridStyle
        {

            /// <remarks/>
            lines,

            /// <remarks/>
            dots,
        }

        /// <remarks/>

        [System.SerializableAttribute()]
        public enum gridDisplay
        {

            /// <remarks/>
            no,

            /// <remarks/>
            yes,
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum gridAltunitdist
        {

            /// <remarks/>
            mic,

            /// <remarks/>
            mm,

            /// <remarks/>
            mil,

            /// <remarks/>
            inch,
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum gridAltunit
        {

            /// <remarks/>
            mic,

            /// <remarks/>
            mm,

            /// <remarks/>
            mil,

            /// <remarks/>
            inch,
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class layers
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("layer")]
            public layer[] layer;
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class layer
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string number;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string name;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string color;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string fill;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(layerVisible.yes)]
            public layerVisible visible;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(layerActive.yes)]
            public layerActive active;

            public layer()
            {
                this.visible = layerVisible.yes;
                this.active = layerActive.yes;
            }
        }

        /// <remarks/>

        [System.SerializableAttribute()]
        public enum layerVisible
        {

            /// <remarks/>
            no,

            /// <remarks/>
            yes,
        }

        /// <remarks/>

        [System.SerializableAttribute()]
        public enum layerActive
        {

            /// <remarks/>
            no,

            /// <remarks/>
            yes,
        }

        /// <remarks/>
        [System.SerializableAttribute()]
        public partial class board
        {

            /// <remarks/>
            public description description;

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("circle", typeof(circle), IsNullable = false)]
            public circle[] circle;
            [System.Xml.Serialization.XmlArrayItemAttribute("dimension", typeof(dimension), IsNullable = false)]
            public dimension[] dimension;
            [System.Xml.Serialization.XmlArrayItemAttribute("frame", typeof(frame), IsNullable = false)]
            public frame[] frame;
            [System.Xml.Serialization.XmlArrayItemAttribute("hole", typeof(hole), IsNullable = false)]
            public hole[] hole;
            [System.Xml.Serialization.XmlArrayItemAttribute("polygon", typeof(polygon), IsNullable = false)]
            public polygon[] polygon;
            [System.Xml.Serialization.XmlArrayItemAttribute("rectangle", typeof(rectangle), IsNullable = false)]
            public rectangle[] rectangle;
            [System.Xml.Serialization.XmlArrayItemAttribute("text", typeof(text), IsNullable = false)]
            public text[] text;
            [System.Xml.Serialization.XmlArrayItemAttribute("wire", typeof(wire), IsNullable = false)]
            public wire[] wire;

            //[System.Xml.Serialization.XmlArrayItemAttribute("plain", typeof(plain), IsNullable = false)]
            public plain plain;

            /// <remarks/>
            public libraries libraries;

            /// <remarks/>
            public attributes attributes;

            /// <remarks/>
            public variantdefs variantdefs;

            /// <remarks/>
            public classes classes;

            /// <remarks/>
            public designrules designrules;

            /// <remarks/>
            public autorouter autorouter;

            /// <remarks/>
            public elements elements;

            /// <remarks/>
            public signals signals;

            /// <remarks/>
            public errors errors;
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class description
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("en")]
            public string language;

            /// <remarks/>
            [System.Xml.Serialization.XmlTextAttribute()]
            public string Value;

            public description()
            {
                this.language = "en";
            }
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class circle
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string x;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string y;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string radius;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string width;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string layer;
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class dimension
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string x1;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string y1;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string x2;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string y2;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string x3;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string y3;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string layer;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(dimensionDtype.parallel)]
            public dimensionDtype dtype;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string width;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("0")]
            public string extwidth;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("0")]
            public string extlength;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("0")]
            public string extoffset;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string textsize;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("8")]
            public string textratio;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(dimensionUnit.mm)]
            public dimensionUnit unit;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("2")]
            public string precision;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(dimensionVisible.no)]
            public dimensionVisible visible;

            public dimension()
            {
                this.dtype = dimensionDtype.parallel;
                this.extwidth = "0";
                this.extlength = "0";
                this.extoffset = "0";
                this.textratio = "8";
                this.unit = dimensionUnit.mm;
                this.precision = "2";
                this.visible = dimensionVisible.no;
            }
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum dimensionDtype
        {

            /// <remarks/>
            parallel,

            /// <remarks/>
            horizontal,

            /// <remarks/>
            vertical,

            /// <remarks/>
            radius,

            /// <remarks/>
            diameter,

            /// <remarks/>
            leader,
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum dimensionUnit
        {

            /// <remarks/>
            mic,

            /// <remarks/>
            mm,

            /// <remarks/>
            mil,

            /// <remarks/>
            inch,
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum dimensionVisible
        {

            /// <remarks/>
            no,

            /// <remarks/>
            yes,
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class frame
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string x1;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string y1;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string x2;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string y2;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string columns;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string rows;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string layer;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute("border-left")]
            [System.ComponentModel.DefaultValueAttribute(frameBorderleft.yes)]
            public frameBorderleft borderleft;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute("border-top")]
            [System.ComponentModel.DefaultValueAttribute(frameBordertop.yes)]
            public frameBordertop bordertop;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute("border-right")]
            [System.ComponentModel.DefaultValueAttribute(frameBorderright.yes)]
            public frameBorderright borderright;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute("border-bottom")]
            [System.ComponentModel.DefaultValueAttribute(frameBorderbottom.yes)]
            public frameBorderbottom borderbottom;

            public frame()
            {
                this.borderleft = frameBorderleft.yes;
                this.bordertop = frameBordertop.yes;
                this.borderright = frameBorderright.yes;
                this.borderbottom = frameBorderbottom.yes;
            }
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum frameBorderleft
        {

            /// <remarks/>
            no,

            /// <remarks/>
            yes,
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum frameBordertop
        {

            /// <remarks/>
            no,

            /// <remarks/>
            yes,
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum frameBorderright
        {

            /// <remarks/>
            no,

            /// <remarks/>
            yes,
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum frameBorderbottom
        {

            /// <remarks/>
            no,

            /// <remarks/>
            yes,
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class hole
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string x;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string y;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string drill;
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class polygon
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("vertex")]
            public vertex[] vertex;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string width;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string layer;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string spacing;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(polygonPour.solid)]
            public polygonPour pour;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string isolate;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(polygonOrphans.no)]
            public polygonOrphans orphans;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(polygonThermals.yes)]
            public polygonThermals thermals;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("0")]
            public string rank;

            public polygon()
            {
                this.pour = polygonPour.solid;
                this.orphans = polygonOrphans.no;
                this.thermals = polygonThermals.yes;
                this.rank = "0";
            }
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class vertex
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string x;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string y;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("0")]
            public string curve;

            public vertex()
            {
                this.curve = "0";
            }
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum polygonPour
        {

            /// <remarks/>
            solid,

            /// <remarks/>
            hatch,

            /// <remarks/>
            cutout,
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum polygonOrphans
        {

            /// <remarks/>
            no,

            /// <remarks/>
            yes,
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum polygonThermals
        {

            /// <remarks/>
            no,

            /// <remarks/>
            yes,
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class rectangle
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string x1;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string y1;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string x2;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string y2;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string layer;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("R0")]
            public string rot;

            public rectangle()
            {
                this.rot = "R0";
            }
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class text
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string x;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string y;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string size;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string layer;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(textFont.proportional)]
            public textFont font;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("8")]
            public string ratio;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("R0")]
            public string rot;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(textAlign.bottomleft)]
            public textAlign align;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("50")]
            public string distance;

            /// <remarks/>
            [System.Xml.Serialization.XmlTextAttribute()]
            public string Value;

            public text()
            {
                this.font = textFont.proportional;
                this.ratio = "8";
                this.rot = "R0";
                this.align = textAlign.bottomleft;
                this.distance = "50";
            }
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum textFont
        {

            /// <remarks/>
            vector,

            /// <remarks/>
            proportional,

            /// <remarks/>
            @fixed,
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum textAlign
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlEnumAttribute("bottom-left")]
            bottomleft,

            /// <remarks/>
            [System.Xml.Serialization.XmlEnumAttribute("bottom-center")]
            bottomcenter,

            /// <remarks/>
            [System.Xml.Serialization.XmlEnumAttribute("bottom-right")]
            bottomright,

            /// <remarks/>
            [System.Xml.Serialization.XmlEnumAttribute("center-left")]
            centerleft,

            /// <remarks/>
            center,

            /// <remarks/>
            [System.Xml.Serialization.XmlEnumAttribute("center-right")]
            centerright,

            /// <remarks/>
            [System.Xml.Serialization.XmlEnumAttribute("top-left")]
            topleft,

            /// <remarks/>
            [System.Xml.Serialization.XmlEnumAttribute("top-center")]
            topcenter,

            /// <remarks/>
            [System.Xml.Serialization.XmlEnumAttribute("top-right")]
            topright,
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class wire
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string x1;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string y1;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string x2;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string y2;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string width;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string layer;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string extent;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(wireStyle.continuous)]
            public wireStyle style;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("0")]
            public string curve;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(wireCap.round)]
            public wireCap cap;

            public wire()
            {
                this.style = wireStyle.continuous;
                this.curve = "0";
                this.cap = wireCap.round;
            }
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum wireStyle
        {

            /// <remarks/>
            continuous,

            /// <remarks/>
            longdash,

            /// <remarks/>
            shortdash,

            /// <remarks/>
            dashdot,
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum wireCap
        {

            /// <remarks/>
            flat,

            /// <remarks/>
            round,
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class libraries
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("library")]
            public library[] library;
        }

        [System.SerializableAttribute()]
        public partial class library
        {

            /// <remarks/>
            public description description;

            /// <remarks/>
            public packages packages;

            /// <remarks/>
            public symbols symbols;

            /// <remarks/>
            public devicesets devicesets;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string name;
        }

        /// <remarks/>
        [System.SerializableAttribute()]
        public partial class packages
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("package")]
            public package[] package;
        }

        /// <remarks/>
        [System.SerializableAttribute()]
        public partial class package
        {

            /// <remarks/>
            public description description;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("circle", typeof(circle))]
            public circle[] circle;
            [System.Xml.Serialization.XmlElementAttribute("dimension", typeof(dimension))]
            public dimension[] dimension;
            [System.Xml.Serialization.XmlElementAttribute("frame", typeof(frame))]
            public frame[] frame;
            [System.Xml.Serialization.XmlElementAttribute("hole", typeof(hole))]
            public hole[] hole;
            [System.Xml.Serialization.XmlElementAttribute("pad", typeof(pad))]
            public pad[] pad;
            [System.Xml.Serialization.XmlElementAttribute("polygon", typeof(polygon))]
            public polygon[] polygon;
            [System.Xml.Serialization.XmlElementAttribute("rectangle", typeof(rectangle))]
            public rectangle[] rectangle;
            [System.Xml.Serialization.XmlElementAttribute("smd", typeof(smd))]
            public smd[] smd;
            [System.Xml.Serialization.XmlElementAttribute("text", typeof(text))]
            public text[] text;
            [System.Xml.Serialization.XmlElementAttribute("wire", typeof(wire))]
            public wire[] wire;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string name;
        }

        /// <remarks/>
        [System.SerializableAttribute()]
        public partial class pad
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string name;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string x;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string y;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string drill;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("0")]
            public string diameter;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(padShape.round)]
            public padShape shape;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("R0")]
            public string rot;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(padStop.yes)]
            public padStop stop;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(padThermals.yes)]
            public padThermals thermals;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(padFirst.no)]
            public padFirst first;

            public pad()
            {
                this.diameter = "0";
                this.shape = padShape.round;
                this.rot = "R0";
                this.stop = padStop.yes;
                this.thermals = padThermals.yes;
                this.first = padFirst.no;
            }
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum padShape
        {

            /// <remarks/>
            square,

            /// <remarks/>
            round,

            /// <remarks/>
            octagon,

            /// <remarks/>
            @long,

            /// <remarks/>
            offset,
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum padStop
        {

            /// <remarks/>
            no,

            /// <remarks/>
            yes,
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum padThermals
        {

            /// <remarks/>
            no,

            /// <remarks/>
            yes,
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum padFirst
        {

            /// <remarks/>
            no,

            /// <remarks/>
            yes,
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class smd
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string name;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string x;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string y;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string dx;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string dy;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string layer;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("0")]
            public string roundness;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("R0")]
            public string rot;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(smdStop.yes)]
            public smdStop stop;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(smdThermals.yes)]
            public smdThermals thermals;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(smdCream.yes)]
            public smdCream cream;

            public smd()
            {
                this.roundness = "0";
                this.rot = "R0";
                this.stop = smdStop.yes;
                this.thermals = smdThermals.yes;
                this.cream = smdCream.yes;
            }
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum smdStop
        {

            /// <remarks/>
            no,

            /// <remarks/>
            yes,
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum smdThermals
        {

            /// <remarks/>
            no,

            /// <remarks/>
            yes,
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum smdCream
        {

            /// <remarks/>
            no,

            /// <remarks/>
            yes,
        }

        [System.SerializableAttribute()]
        public partial class symbols
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("symbol")]
            public symbol[] symbol;
        }

        [System.SerializableAttribute()]
        public partial class symbol
        {

            /// <remarks/>
            public description description;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("circle", typeof(circle))]
            public circle[] circle;
            [System.Xml.Serialization.XmlElementAttribute("dimension", typeof(dimension))]
            public dimension[] dimension;
            [System.Xml.Serialization.XmlElementAttribute("frame", typeof(frame))]
            public frame[] frame;
            [System.Xml.Serialization.XmlElementAttribute("pin", typeof(pin))]
            public pin[] pin;
            [System.Xml.Serialization.XmlElementAttribute("polygon", typeof(polygon))]
            public polygon[] polygon;
            [System.Xml.Serialization.XmlElementAttribute("rectangle", typeof(rectangle))]
            public rectangle[] rectangle;
            [System.Xml.Serialization.XmlElementAttribute("text", typeof(text))]
            public text[] text;
            [System.Xml.Serialization.XmlElementAttribute("wire", typeof(wire))]
            public wire[] wire;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string name;
        }

        [System.SerializableAttribute()]
        public partial class pin
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string name;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string x;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string y;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(pinVisible.both)]
            public pinVisible visible;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(pinLength.@long)]
            public pinLength length;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(pinDirection.io)]
            public pinDirection direction;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(pinFunction.none)]
            public pinFunction function;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("0")]
            public string swaplevel;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("R0")]
            public string rot;

            public pin()
            {
                this.visible = pinVisible.both;
                this.length = pinLength.@long;
                this.direction = pinDirection.io;
                this.function = pinFunction.none;
                this.swaplevel = "0";
                this.rot = "R0";
            }
        }

        [System.SerializableAttribute()]
        public enum pinVisible
        {

            /// <remarks/>
            off,

            /// <remarks/>
            pad,

            /// <remarks/>
            pin,

            /// <remarks/>
            both,
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum pinLength
        {

            /// <remarks/>
            point,

            /// <remarks/>
            @short,

            /// <remarks/>
            middle,

            /// <remarks/>
            @long,
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum pinDirection
        {

            /// <remarks/>
            nc,

            /// <remarks/>
            @in,

            /// <remarks/>
            @out,

            /// <remarks/>
            io,

            /// <remarks/>
            oc,

            /// <remarks/>
            pwr,

            /// <remarks/>
            pas,

            /// <remarks/>
            hiz,

            /// <remarks/>
            sup,
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum pinFunction
        {

            /// <remarks/>
            none,

            /// <remarks/>
            dot,

            /// <remarks/>
            clk,

            /// <remarks/>
            dotclk,
        }

        [System.SerializableAttribute()]
        public partial class devicesets
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("deviceset")]
            public deviceset[] deviceset;
        }

        [System.SerializableAttribute()]
        public partial class deviceset
        {

            /// <remarks/>
            public description description;

            /// <remarks/>
            public gates gates;

            /// <remarks/>
            public devices devices;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string name;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("")]
            public string prefix;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(devicesetUservalue.no)]
            public devicesetUservalue uservalue;

            public deviceset()
            {
                this.prefix = "";
                this.uservalue = devicesetUservalue.no;
            }
        }

        [System.SerializableAttribute()]
        public partial class gates
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("gate")]
            public gate[] gate;
        }

        [System.SerializableAttribute()]
        public partial class gate
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string name;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string symbol;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string x;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string y;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public gateAddlevel addlevel;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]

            public string swaplevel;

            public gate()
            {
                this.addlevel = gateAddlevel.next;
                this.swaplevel = "0";
            }
        }

        [System.SerializableAttribute()]
        public enum gateAddlevel
        {

            /// <remarks/>
            must,

            /// <remarks/>
            can,

            /// <remarks/>
            next,

            /// <remarks/>
            request,

            /// <remarks/>
            always,
        }

        /// <remarks/>
        [System.SerializableAttribute()]
        public partial class devices
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("device")]
            public device[] device;
        }

        [System.SerializableAttribute()]
        public partial class device
        {

            /// <remarks/>
            public connects connects;

            /// <remarks/>
            public technologies technologies;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("")]
            public string name;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string package;

            public device()
            {
                this.name = "";
            }
        }

        [System.SerializableAttribute()]
        public partial class connects
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("connect")]
            public connect[] connect;
        }

        [System.SerializableAttribute()]
        public partial class connect
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string gate;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string pin;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string pad;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(connectRoute.all)]
            public connectRoute route;

            public connect()
            {
                this.route = connectRoute.all;
            }
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum connectRoute
        {

            /// <remarks/>
            all,

            /// <remarks/>
            any,
        }

        /// <remarks/>
        [System.SerializableAttribute()]
        public partial class technologies
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("technology")]
            public technology[] technology;
        }

        [System.SerializableAttribute()]
        public partial class technology
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("attribute")]
            public attribute[] attribute;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string name;
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public partial class attribute
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string name;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string value;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string x;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string y;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string size;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string layer;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public attributeFont font;

            /// <remarks/>
            [System.Xml.Serialization.XmlIgnoreAttribute()]
            public bool fontSpecified;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string ratio;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("R0")]
            public string rot;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(attributeDisplay.value)]
            public attributeDisplay display;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(attributeConstant.no)]
            public attributeConstant constant;

            public attribute()
            {
                this.rot = "R0";
                this.display = attributeDisplay.value;
                this.constant = attributeConstant.no;
            }
        }

        /// <remarks/>

        [System.SerializableAttribute()]
        public enum attributeFont
        {

            /// <remarks/>
            vector,

            /// <remarks/>
            proportional,

            /// <remarks/>
            @fixed,
        }

        /// <remarks/>

        [System.SerializableAttribute()]
        public enum attributeDisplay
        {

            /// <remarks/>
            off,

            /// <remarks/>
            value,

            /// <remarks/>
            name,

            /// <remarks/>
            both,
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum attributeConstant
        {

            /// <remarks/>
            no,

            /// <remarks/>
            yes,
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum devicesetUservalue
        {

            /// <remarks/>
            no,

            /// <remarks/>
            yes,
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class attributes
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("attribute")]
            public attribute[] attribute;
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class variantdefs
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("variantdef")]
            public variantdef[] variantdef;
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class variantdef
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string name;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(variantdefCurrent.no)]
            public variantdefCurrent current;

            public variantdef()
            {
                this.current = variantdefCurrent.no;
            }
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum variantdefCurrent
        {

            /// <remarks/>
            no,

            /// <remarks/>
            yes,
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class classes
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("class")]
            public @class[] @class;
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class @class
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("clearance")]
            public clearance[] clearance;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string number;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string name;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("0")]
            public string width;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("0")]
            public string drill;

            public @class()
            {
                this.width = "0";
                this.drill = "0";
            }
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class clearance
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string @class;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("0")]
            public string value;

            public clearance()
            {
                this.value = "0";
            }
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class designrules
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("description")]
            public description[] description;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("param")]
            public param[] param;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string name;
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class param
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string name;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string value;
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class autorouter
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("pass")]
            public pass[] pass;
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class pass
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("param")]
            public param[] param;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string name;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string refer;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(passActive.yes)]
            public passActive active;

            public pass()
            {
                this.active = passActive.yes;
            }
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum passActive
        {

            /// <remarks/>
            no,

            /// <remarks/>
            yes,
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class elements
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("element")]
            public element[] element;
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class element
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("attribute")]
            public attribute[] attribute;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("variant")]
            public variant[] variant;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string name;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string library;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string package;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string value;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string x;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string y;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(elementLocked.no)]
            public elementLocked locked;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(elementPopulate.yes)]
            public elementPopulate populate;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(elementSmashed.no)]
            public elementSmashed smashed;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("R0")]
            public string rot;

            public element()
            {
                this.locked = elementLocked.no;
                this.populate = elementPopulate.yes;
                this.smashed = elementSmashed.no;
                this.rot = "R0";
            }
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class variant
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string name;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(variantPopulate.yes)]
            public variantPopulate populate;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string value;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string technology;

            public variant()
            {
                this.populate = variantPopulate.yes;
            }
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum variantPopulate
        {

            /// <remarks/>
            no,

            /// <remarks/>
            yes,
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum elementLocked
        {

            /// <remarks/>
            no,

            /// <remarks/>
            yes,
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum elementPopulate
        {

            /// <remarks/>
            no,

            /// <remarks/>
            yes,
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum elementSmashed
        {

            /// <remarks/>
            no,

            /// <remarks/>
            yes,
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class signals
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("signal")]
            public signal[] signal;
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class signal
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("contactref", typeof(contactref))]
            public contactref[] contactref;
            [System.Xml.Serialization.XmlElementAttribute("polygon", typeof(polygon))]
            public polygon[] polygon;
            [System.Xml.Serialization.XmlElementAttribute("via", typeof(via))]
            public via[] via;
            [System.Xml.Serialization.XmlElementAttribute("wire", typeof(wire))]
            public wire[] wire;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string name;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("0")]
            public string @class;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(signalAirwireshidden.no)]
            public signalAirwireshidden airwireshidden;

            public signal()
            {
                this.@class = "0";
                this.airwireshidden = signalAirwireshidden.no;
            }
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class contactref
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string element;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string pad;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(contactrefRoute.all)]
            public contactrefRoute route;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("")]
            public string routetag;

            public contactref()
            {
                this.route = contactrefRoute.all;
                this.routetag = "";
            }
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum contactrefRoute
        {

            /// <remarks/>
            all,

            /// <remarks/>
            any,
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class via
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string x;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string y;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string extent;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string drill;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("0")]
            public string diameter;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(viaShape.round)]
            public viaShape shape;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(viaAlwaysstop.no)]
            public viaAlwaysstop alwaysstop;

            public via()
            {
                this.diameter = "0";
                this.shape = viaShape.round;
                this.alwaysstop = viaAlwaysstop.no;
            }
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum viaShape
        {

            /// <remarks/>
            square,

            /// <remarks/>
            round,

            /// <remarks/>
            octagon,
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum viaAlwaysstop
        {

            /// <remarks/>
            no,

            /// <remarks/>
            yes,
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum signalAirwireshidden
        {

            /// <remarks/>
            no,

            /// <remarks/>
            yes,
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class errors
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("approved")]
            public approved[] approved;
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class approved
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string hash;
        }

        [System.SerializableAttribute()]
        public partial class schematic
        {

            /// <remarks/>
            public description description;

            /// <remarks/>
            public libraries libraries;

            /// <remarks/>
            public attributes attributes;

            /// <remarks/>
            public variantdefs variantdefs;

            /// <remarks/>
            public classes classes;

            /// <remarks/>
            public modules modules;

            /// <remarks/>
            public parts parts;

            /// <remarks/>
            public sheets sheets;

            /// <remarks/>
            public errors errors;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string xreflabel;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string xrefpart;
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class modules
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("module")]
            public module[] module;
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class module
        {

            /// <remarks/>
            public description description;

            /// <remarks/>
            public ports ports;

            /// <remarks/>
            public variantdefs variantdefs;

            /// <remarks/>
            public parts parts;

            /// <remarks/>
            public sheets sheets;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string name;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("")]
            public string prefix;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string dx;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string dy;

            public module()
            {
                this.prefix = "";
            }
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class ports
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("port")]
            public port[] port;
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class port
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string name;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string side;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string coord;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(portDirection.io)]
            public portDirection direction;

            public port()
            {
                this.direction = portDirection.io;
            }
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum portDirection
        {

            /// <remarks/>
            nc,

            /// <remarks/>
            @in,

            /// <remarks/>
            @out,

            /// <remarks/>
            io,

            /// <remarks/>
            oc,

            /// <remarks/>
            pwr,

            /// <remarks/>
            pas,

            /// <remarks/>
            hiz,
        }

        /// <remarks/>
        [System.SerializableAttribute()]
        public partial class parts
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("part")]
            public part[] part;
        }

        [System.SerializableAttribute()]
        public partial class part
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("attribute")]
            public attribute[] attribute;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("variant")]
            public variant[] variant;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string name;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string library;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string deviceset;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string device;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("")]
            public string technology;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string value;

            public part()
            {
                this.technology = "";
            }
        }

        [System.SerializableAttribute()]
        public partial class sheets
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("sheet")]
            public sheet[] sheet;
        }

        [System.SerializableAttribute()]
        public partial class sheet
        {

            /// <remarks/>
            public description description;

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("circle", typeof(circle), IsNullable = false)]
            public circle[] circle;
            [System.Xml.Serialization.XmlArrayItemAttribute("dimension", typeof(dimension), IsNullable = false)]
            public dimension[] dimension;
            [System.Xml.Serialization.XmlArrayItemAttribute("frame", typeof(frame), IsNullable = false)]
            public frame[] frame;
            [System.Xml.Serialization.XmlArrayItemAttribute("hole", typeof(hole), IsNullable = false)]
            public hole[] hole;
            [System.Xml.Serialization.XmlArrayItemAttribute("polygon", typeof(polygon), IsNullable = false)]
            public polygon[] polygon;
            [System.Xml.Serialization.XmlArrayItemAttribute("rectangle", typeof(rectangle), IsNullable = false)]
            public rectangle[] rectangle;
            [System.Xml.Serialization.XmlArrayItemAttribute("text", typeof(text), IsNullable = false)]
            public text[] text;
            [System.Xml.Serialization.XmlArrayItemAttribute("wire", typeof(wire), IsNullable = false)]
            public wire[] wire;

            [System.Xml.Serialization.XmlArrayItemAttribute("plain", typeof(plain), IsNullable = false)]
            public plain[] plain;

            /// <remarks/>
            public moduleinsts moduleinsts;

            /// <remarks/>
            public instances instances;

            /// <remarks/>
            public busses busses;

            /// <remarks/>
            public nets nets;
        }

        /// <remarks/>
        [System.SerializableAttribute()]
        public partial class moduleinsts
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("moduleinst")]
            public moduleinst[] moduleinst;
        }

        /// <remarks/>
        [System.SerializableAttribute()]
        public partial class moduleinst
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("attribute")]
            public attribute[] attribute;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string name;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string module;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("")]
            public string modulevariant;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string x;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string y;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("0")]
            public string offset;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(moduleinstSmashed.no)]
            public moduleinstSmashed smashed;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("R0")]
            public string rot;

            public moduleinst()
            {
                this.modulevariant = "";
                this.offset = "0";
                this.smashed = moduleinstSmashed.no;
                this.rot = "R0";
            }
        }

        [System.SerializableAttribute()]
        public enum moduleinstSmashed
        {

            /// <remarks/>
            no,

            /// <remarks/>
            yes,
        }

        [System.SerializableAttribute()]
        public partial class instances
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("instance")]
            public instance[] instance;
        }

        [System.SerializableAttribute()]
        public partial class instance
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("attribute")]
            public attribute[] attribute;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string part;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string gate;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string x;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string y;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(instanceSmashed.no)]
            public instanceSmashed smashed;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("R0")]
            public string rot;

            public instance()
            {
                this.smashed = instanceSmashed.no;
                this.rot = "R0";
            }
        }

        [System.SerializableAttribute()]
        public enum instanceSmashed
        {

            /// <remarks/>
            no,

            /// <remarks/>
            yes,
        }

        [System.SerializableAttribute()]
        public partial class busses
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("bus")]
            public bus[] bus;
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class bus
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("junction", typeof(junction), IsNullable = false)]
            public junction[] junction;
            [System.Xml.Serialization.XmlArrayItemAttribute("label", typeof(label), IsNullable = false)]
            public label[] label;
            [System.Xml.Serialization.XmlArrayItemAttribute("pinref", typeof(pinref), IsNullable = false)]
            public pinref[] pinref;
            [System.Xml.Serialization.XmlArrayItemAttribute("portref", typeof(portref), IsNullable = false)]
            public portref[] portref;
            [System.Xml.Serialization.XmlArrayItemAttribute("wire", typeof(wire), IsNullable = false)]
            public wire[] wire;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string name;
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class junction
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string x;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string y;
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class label
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string x;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string y;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string size;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string layer;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(labelFont.proportional)]
            public labelFont font;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("8")]
            public string ratio;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("R0")]
            public string rot;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(labelXref.no)]
            public labelXref xref;

            public label()
            {
                this.font = labelFont.proportional;
                this.ratio = "8";
                this.rot = "R0";
                this.xref = labelXref.no;
            }
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum labelFont
        {

            /// <remarks/>
            vector,

            /// <remarks/>
            proportional,

            /// <remarks/>
            @fixed,
        }

        /// <remarks/>

        [System.SerializableAttribute()]

        public enum labelXref
        {

            /// <remarks/>
            no,

            /// <remarks/>
            yes,
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class pinref
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string part;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string gate;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string pin;
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class portref
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string moduleinst;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string port;
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class nets
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("net")]
            public net[] net;
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class net
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("junction", typeof(junction), IsNullable = false)]
            public junction[] junction;
            [System.Xml.Serialization.XmlArrayItemAttribute("label", typeof(label), IsNullable = false)]
            public label[] label;
            [System.Xml.Serialization.XmlArrayItemAttribute("pinref", typeof(pinref), IsNullable = false)]
            public pinref[] pinref;
            [System.Xml.Serialization.XmlArrayItemAttribute("portref", typeof(portref), IsNullable = false)]
            public portref[] portref;
            [System.Xml.Serialization.XmlArrayItemAttribute("wire", typeof(wire), IsNullable = false)]
            public wire[] wire;

            [System.Xml.Serialization.XmlArrayItemAttribute("segment", typeof(segment), IsNullable = false)]
            public segment[] segment;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string name;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("0")]
            public string @class;

            public net()
            {
                this.@class = "0";
            }
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class segment
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("junction", typeof(junction))]
            public junction[] junction;
            [System.Xml.Serialization.XmlElementAttribute("label", typeof(label))]
            public label[] label;
            [System.Xml.Serialization.XmlElementAttribute("pinref", typeof(pinref))]
            public pinref[] pinref;
            [System.Xml.Serialization.XmlElementAttribute("portref", typeof(portref))]
            public portref[] portref;
            [System.Xml.Serialization.XmlElementAttribute("wire", typeof(wire))]
            public wire[] wire;
        }

        /// <remarks/>

        [System.SerializableAttribute()]




        public partial class plain
        {

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("circle", typeof(circle))]
            public circle[] circle;
            [System.Xml.Serialization.XmlElementAttribute("dimension", typeof(dimension))]
            public dimension[] dimension;
            [System.Xml.Serialization.XmlElementAttribute("frame", typeof(frame))]
            public frame[] frame;
            [System.Xml.Serialization.XmlElementAttribute("hole", typeof(hole))]
            public hole[] hole;
            [System.Xml.Serialization.XmlElementAttribute("polygon", typeof(polygon))]
            public polygon[] polygon;
            [System.Xml.Serialization.XmlElementAttribute("rectangle", typeof(rectangle))]
            public rectangle[] rectangle;
            [System.Xml.Serialization.XmlElementAttribute("text", typeof(text))]
            public text[] text;
            [System.Xml.Serialization.XmlElementAttribute("wire", typeof(wire))]
            public wire[] wire;
        }
    }
}